name: CT & e2e Tests
# run workflow on git push and git pull
on: [push, pull_request]
jobs:
  component-run:
    # OS
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other containers, because this will kill Cypress processes leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout code
        # checks-out your repository so your workflow can access it
        uses: actions/checkout@v2
      - name: Run Component tests
        # GitHub Action for running Cypress end-to-end tests
        uses: cypress-io/github-action@v3
        with:
          # when using custom cypress run command, options must be passed manually via command or script
          command: npm run component:parallel
          # config option option required when using Cypress v10+ or cypress-io/github-action@v3+
          config-file: cypress.config.js
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the Dashboard project id as an environment variable
          CYPRESS_PROJECT_ID:  ${{ secrets.CYPRESS_PROJECT_ID }}
          # Recommended: pass the GitHub token lets this action correctly determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # - if the event is push, the title will be undefined and Cypress will get the commit message from Git information
          # - if the event is pull_request, then we set the commit message to the pull request title
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          #This will allow Cypress bot to show in addition to status checks
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}


jobs:
  e2e-run:
    # OS
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other containers, because this will kill Cypress processes leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2, 3]
    steps:
      - name: Checkout code
        # checks-out your repository so your workflow can access it
        uses: actions/checkout@v2
      - name: Run E2E tests
        # GitHub Action for running Cypress end-to-end tests
        uses: cypress-io/github-action@v3
        with:
          record: true
          parallel: true
          tag: parallel, e2e
          # config option option required when using Cypress v10+ or cypress-io/github-action@v3+
          config-file: cypress.config.js
          browser: chrome
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass the Dashboard project id as an environment variable
          CYPRESS_PROJECT_ID:  ${{ secrets.CYPRESS_PROJECT_ID }}
          # Recommended: pass the GitHub token lets this action correctly determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # - if the event is push, the title will be undefined and Cypress will get the commit message from Git information
          # - if the event is pull_request, then we set the commit message to the pull request title
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          #This will allow Cypress bot to show in addition to status checks
          COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}